# Site settings
title: Saser
description: > # this means to ignore newlines until "baseurl:"
    20 years old student from Sweden, studying software engineering at Chalmers University of Technology. On this blog I mostly write about my software projects, as well as my thoughts on the meaning of life and other non-important stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://saser.github.io/" # the base hostname & protocol for your site
twitter_username: Saser_
github_username:  Saser
timezone: Europe/Stockholm

# Build settings
markdown: kramdown
